package com.example.laptop.components;

public enum ASSEMBLYCOMPONENTTYPE {
    MOTHERBOARD,
    MOTHERBOARD_CPU,
    GRAPHICS_CARD,
    GRAPHICS_SCREEN,
    STORAGE_HARD_DISC,
    POWER_BATTERY,
    POWER_AC_ADAPTER,
    MOTHERBOARD_RAM,
    GRAPHICS_ASSEMBLY,
    MOTHERBOARD_ASSEMBLY,
    POWER_ASSEMBLY,
    STORAGE_ASSEMBLY,
    LAPTOP
}
